create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text unique,
  full_name text,
  bio text,
  role text check (role in ('customer', 'shopkeeper')),
  public_profile_url text not null unique,
  image_url text,
  public_data jsonb not null default '{}'::jsonb,
  protected_data jsonb not null default '{}'::jsonb,
  protected_url text,
  instagram_url text,
  whatsapp_number text,
  linkedin_url text,
  pitch_deck_url text,
  permission text not null default 'no',
  is_ticket_paid boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance numeric not null default 0,
  currency text not null default 'INR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.otp_verifications (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_verified boolean not null default false,
  phone_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ring_id text not null unique,
  nickname text not null default '',            
  status text not null default 'active'           -- this is valid for the payment part only
    check (status in ('active', 'temp_blocked', 'permanent_blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_devices (
  id uuid primary key default gen_random_uuid(),
  mac_address text not null unique,
  location text,
  shopkeeper_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid references public.organizations(id) on delete cascade,
  reader_type text default 'payment',
  device_secret text,
  hardware_uid text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ring_id uuid references public.rings(id) on delete set null,
  amount numeric not null,
  type text not null check (type in ('payment', 'refund', 'topup')),
  organization_id uuid references public.organizations(id) on delete set null,
  description text,
  merchant text,
  category text,
  location text,
  status text not null default 'completed',
  created_at timestamptz not null default now()
);

create table if not exists public.user_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  organization_id uuid references public.organizations(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.verification_credentials (
  id bigint generated by default as identity primary key,
  mac_address text not null unique,
  lat double precision not null,
  lng double precision not null,
  radius_m integer not null default 200,
  label text,
  nfc_id text,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.ring_device_access (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null references public.user_profiles(user_id) on delete cascade,
  ring_id text not null,

  mac_address text not null,
  shopkeeper_id uuid not null references auth.users(id) on delete cascade,

  status text not null default 'active'
    check (status in ('active', 'inactive', 'revoked')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ring_device_access_unique unique (ring_id, mac_address, shopkeeper_id)
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role text not null check (role in ('user', 'minor_admin', 'admin')),
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table public.reader_access (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  ring_id text not null,
  reader_id uuid not null references public.payment_devices(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (ring_id, reader_id)
);